import fs from 'node:fs';
import path from 'node:path';
import PDFDocument from 'pdfkit';
import type { Response } from 'express';
import type { Product } from '../product/product.entity';
import { dualCurrency } from '../common/utils/currency';
import type { Supplier } from '../supplier/supplier.entity';
import type { PurchaseItem } from './purchase-item.entity';
import type { Purchase } from './purchase.entity';

function getArabicFontPath() {
  const fontPaths = [
    path.join(process.cwd(), 'src/assets/fonts/arabic.ttf'),
    path.join(process.cwd(), 'dist/assets/fonts/arabic.ttf'),
    path.join(__dirname, '../assets/fonts/arabic.ttf'),
  ];

  return fontPaths.find((fontPath) => fs.existsSync(fontPath)) ?? fontPaths[0];
}

export function generatePurchasePDF(
  purchase: Purchase,
  items: PurchaseItem[],
  supplier: Supplier,
  products: Product[],
  res: Response,
  kwdToUsdRate?: number,
) {
  const doc = new PDFDocument({ margin: 32 });
  doc.registerFont('Arabic', getArabicFontPath());
  const productNameById = new Map(
    products.map((product) => [product.id, product.name]),
  );

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=purchase-${purchase.id}.pdf`,
  );

  doc.pipe(res);

  doc.font('Helvetica-Bold').fontSize(18).text('Purchase Invoice');
  doc.font('Arabic').fontSize(16).text('فاتورة شراء', { align: 'right' });
  doc.moveDown(0.5);
  doc
    .font('Helvetica')
    .fontSize(10)
    .text('Al-Majad Al-Basat Selling Meat Company');
  doc.text('Shuwaikh Industrial Area, Block 1, Street 71');
  doc.text('Phone: 96684998 / 94942708');

  doc.moveDown();
  doc.font('Helvetica-Bold').fontSize(12).text(`Purchase #${purchase.id}`);
  doc.font('Helvetica').fontSize(10);
  doc.text(`Supplier: ${supplier.name}`);
  doc.text(`Mobile: ${supplier.mobile ?? '-'}`);
  doc.text(`Supplier Invoice: ${purchase.invoice_no ?? '-'}`);
  doc.text(`Purchase Date: ${purchase.purchase_date ?? new Date(purchase.date).toLocaleDateString()}`);
  doc.text(`Goods Received: ${purchase.goods_received_date ?? purchase.purchase_date ?? new Date(purchase.date).toLocaleDateString()}`);
  doc.text(`Recorded At: ${new Date(purchase.date).toLocaleString()}`);

  doc.moveDown();

  const startX = 32;
  let y = doc.y;
  const col = {
    product: startX,
    pieces: 220,
    weight: 285,
    cost: 370,
    amount: 470,
  };

  doc.font('Helvetica-Bold').fontSize(10);
  doc.text('Product', col.product, y);
  doc.text('Pieces', col.pieces, y);
  doc.text('Weight', col.weight, y);
  doc.text('Cost / kg', col.cost, y);
  doc.text('Amount', col.amount, y);

  y += 22;
  doc.moveTo(startX, y).lineTo(560, y).stroke();
  y += 10;

  doc.font('Helvetica').fontSize(10);
  items.forEach((item) => {
    doc.text(
      productNameById.get(item.product_id) ?? `Product #${item.product_id}`,
      col.product,
      y,
      { width: 180 },
    );
    doc.text(String(item.pieces ?? '-'), col.pieces, y);
    doc.text(Number(item.weight).toFixed(3), col.weight, y);
    doc.text(dualCurrency(item.cost_per_kg, kwdToUsdRate), col.cost, y, { width: 95 });
    doc.text(dualCurrency(item.amount, kwdToUsdRate), col.amount, y, { width: 90 });
    y += 28;
  });

  doc.moveTo(startX, y).lineTo(560, y).stroke();
  y += 18;

  doc.font('Helvetica-Bold');
  doc.text('Subtotal', col.cost, y);
  doc.text(dualCurrency(purchase.subtotal ?? purchase.total, kwdToUsdRate), col.amount, y, { width: 90 });
  y += 18;

  if (Number(purchase.discount_amount ?? 0) > 0) {
    doc.text(`Discount ${Number(purchase.discount_percent ?? 0).toFixed(2)}%`, col.cost, y);
    doc.text(`-${dualCurrency(purchase.discount_amount, kwdToUsdRate)}`, col.amount, y, { width: 90 });
    y += 18;
  }

  doc.text('Net Total', col.cost, y);
  doc.text(dualCurrency(purchase.total, kwdToUsdRate), col.amount, y, { width: 90 });
  y += 18;

  if (Number(purchase.advance_paid ?? 0) > 0) {
    doc.text('Advance Paid', col.cost, y);
    doc.text(`-${dualCurrency(purchase.advance_paid, kwdToUsdRate)}`, col.amount, y, { width: 90 });
    y += 18;
  }

  doc.text('Supplier Credit Balance', col.cost, y);
  doc.text(dualCurrency(purchase.balance_due ?? purchase.total, kwdToUsdRate), col.amount, y, { width: 90 });

  doc.moveDown(4);
  doc
    .font('Helvetica')
    .fontSize(8)
    .text('Generated by Meatena Operations Platform', {
      align: 'center',
    });

  doc.end();
}
